# EMR Cluster Configuration
# This file defines the EMR clusters available for monitoring

staging:
  name: "Staging EMR"
  spark_url: "http://staging-master:18080"
  yarn_url: "http://staging-master:8088"
  description: "Staging EMR cluster for development and testing"

production:
  name: "Production EMR"
  spark_url: "http://prod-master:18080"
  yarn_url: "http://prod-master:8088"
  description: "Production EMR cluster for live workloads"

development:
  name: "Development EMR"
  spark_url: "http://dev-master:18080"
  yarn_url: "http://dev-master:8088"
  description: "Development EMR cluster for experimental work"

analytics:
  name: "Analytics EMR"
  spark_url: "http://analytics-master:18080"
  yarn_url: "http://analytics-master:8088"
  description: "Dedicated cluster for analytics and reporting"

# You can also use JSON format instead:
# {
#   "staging": {
#     "name": "Staging EMR",
#     "spark_url": "http://staging-master:18080",
#     "yarn_url": "http://staging-master:8088",
#     "description": "Staging EMR cluster"
#   },
#   "production": {
#     "name": "Production EMR",
#     "spark_url": "http://prod-master:18080",
#     "yarn_url": "http://prod-master:8088",
#     "description": "Production EMR cluster"
#   }
# }